# Use Node.js as the base image
FROM node:lts-alpine AS builder

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the application code
COPY . .

# Build the application
RUN npm run build

# Use a smaller Node.js image for the final stage
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy built files from builder stage
COPY --from=builder /app/.output /app/.output

# Expose port 3000
EXPOSE 3000

# Start the Nuxt app
CMD ["node", ".output/server/index.mjs"]
