FROM node:18-alpine AS build

ENV NODE_ENV=production

WORKDIR /app

COPY app/package.json app/package-lock.json ./
RUN npm ci

COPY app ./
RUN npm run build

FROM nginx:stable-alpine AS production

ENV NODE_ENV=production
WORKDIR /usr/share/nginx/html
COPY --from=build /app/build ./

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
